services:
  baah:
    build:
      context: .
      # dockerfile: Dockerfile.CN
    volumes:
      - ./BAAH_CONFIGS:/app/BAAH_CONFIGS
    # environment:
    #   - HOST=0.0.0.0
    #   - PORT=8000
    #   - TOKEN=YOUR_TOKEN
    ports:
      - 8000:8000
